mail_logs:
  - /var/log/mail.log
  - /var/log/maillog
  - /var/log/exim/main.log
  - /var/log/dovecot.log

dns_logs:
  - /var/log/named/query.log
  - /var/log/unbound.log
  - /var/log/dnsmasq.log
  - /var/log/pihole.log

syslog:
  - /var/log/syslog
  - /var/log/auth.log
